baseURL = 'https://events.ksridhar.dev'
languageCode = 'en-us'
title = 'Hyderabad Tech Events'
theme = 'paper'
paginate = 10

[params]
# color style
color = 'linen'                  # linen, wheat, gray, light
googleAnalytics = 'G-727NLMKDW2'


# misc
disableHLJS = true                       # disable highlight.js
monoDarkIcon = true                      # show monochrome dark mode icon
gravatarCdn = 'GRAVATAR_CDN_LINK'        # e.g. 'https://cdn.v2ex.com/gravatar/'
graphCommentId = "YOUR_GRAPH_COMMENT_ID" # use graph comment (disqus alternative)
math = true                              # enable KaTex math typesetting globally
